spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:order}
    password: ${SPRING_DATASOURCE_PASSWORD:orderpw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # Kafka 발행자(producer) -> 값은 JSON으로 직렬화
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: ${SERVER_PORT:8080}

# compose: http://product-service:8080 / 로컬 IDE 실행: http://localhost:8081
product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db

logging:
  level:
    org.hibernate.SQL: debug