# payment-db 자격증명(Secret) — 같은 패턴, 값만 payment용
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: commerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpw"
  MYSQL_DATABASE: "paymentdb"
  MYSQL_USER: "payment"
  MYSQL_PASSWORD: "paymentpw"