# product-db 자격증명(Secret)
apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: commerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpw"
  MYSQL_DATABASE: "product"
  MYSQL_USER: "product"
  MYSQL_PASSWORD: "productpw"